config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {registrations: 'registrations',
                                      omniauth_callbacks: 'callbacks'}
  resources :events
  resources :event_joinings, only: [:create, :destroy]
  resources :invitations, only: [:index, :create] do
    member do
      post :accept
      post :reject
    end
  end
  resources :users, only: [:index]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  # another way to define routes: get '/events/:id', to: 'events#show', as: 'custom_event'
  root "events#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Host Events</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= favicon_link_tag 'icons8-event-96.png' %>
  </head>

  <body class="bg-gray-100 min-h-screen flex flex-col">
  <nav class="bg-white shadow">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <div class="flex justify-between h-16">
        <div class="flex">
          <div class="flex-shrink-0 flex items-center">
            <h1 class="text-2xl font-bold">
              <%= link_to 'Host Events', root_path, class: 'glow-link' %>
            </h1>
          </div>
        </div>
        <div class="flex items-center">
          <% if !user_signed_in? %>
            <div class="ml-4 flex items-center md:ml-6">
              <%= button_to "Log In", new_user_session_url, method: "get", class: 'bg-indigo-600 hover:bg-indigo-700 text-white font-bold py-2 px-4 rounded' %>
              <%= button_to "Sign Up", new_user_registration_url, method: "get", class: 'ml-3 bg-indigo-600 hover:bg-indigo-700 text-white font-bold py-2 px-4 rounded' %>
            </div>
          <% else %>
            <div class="ml-4 flex items-center md:ml-6">
              <p class="text-gray-600">
                <%= "Currently signed in as: #{current_user.full_name}" %>
              </p>
              <%= button_to "Log Out", destroy_user_session_url, method: "delete", class: 'ml-3 bg-red-600 hover:bg-red-700 text-white font-bold py-2 px-4 rounded' %>
              <%= link_to "Create a New Event", new_event_path, class: 'ml-3 bg-indigo-600 hover:bg-indigo-700 text-white font-bold py-2 px-4 rounded' %>
              <%= link_to "Invitations(#{@invitations_counter})", invitations_path, class: 'ml-3 bg-gray-600 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded' %>
              <%= link_to "Event Hub", users_path, class: 'ml-3 bg-gray-600 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </nav>

  <% if alert || notice %>
    <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded mt-4 mx-auto max-w-7xl" role="alert">
      <% if notice %>
        <p><%= notice %></p>
      <% end %>
      <% if alert %>
        <p><%= alert %></p>
      <% end %>
    </div>
  <% end %>

  <main class="flex-grow mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 mt-8">
    <%= yield %>
  </main>
  </body>
</html>